export const ROLE_PREFIX = 'ROLE_';

export enum Roles {
    RECEIVING = 'RECEIVING',
    INITIAL_RECEIVING = 'INITIAL_RECEIVING',
    RETURNS = 'RETURNS',
    AUTOSTART = 'AUTOSTART',
    SHELFLIFE = 'SHELFLIFE',
    PACKING = 'PACKING',
    DROPPING = 'DROPPING',
    TESTER = 'TESTER',
    NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',
    UIT_SETTINGS = 'UIT_SETTINGS',
    UIT_FREE = 'UIT_FREE',
    SCE_ADMIN = 'SCE_ADMIN',
    SCE_CLERK = 'SCE_CLERK',
    ANOMALY_CONSOLIDATION = 'ANOMALY_CONSOLIDATION',
    PICKING = 'PICKING',
    MULTI_PICKING = 'MULTI_PICKING',
    SCE_RF_USER = 'SCE_RF_USER',
    ANOMALY_ADMIN = 'ANOMALY_ADMIN',
    UIT_REPRINT = 'UIT_REPRINT',
    OUTBOUND_CLERK = 'OUTBOUND_CLERK',
    ANOMALY_RELOCATION = 'ANOMALY_RELOCATION',
    SHIPMENT = 'SHIPMENT',
    CONVEYOR_TESTER = 'CONVEYOR_TESTER',
    SORTER_ADMIN = 'SORTER_ADMIN',
    INVENTORIZATION = 'INVENTORIZATION',
    RECEIVING_TRANSPORT_ADMIN = 'RECEIVING_TRANSPORT_ADMIN',
    PLACEMENT = 'PLACEMENT',
    MANUAL_WAVES = 'MANUAL_WAVES',
    DELETE_UIT = 'DELETE_UIT',
    RECEIVING_CONVEYOR_OPERATOR = 'RECEIVING_CONVEYOR_OPERATOR',
    PHYSICAL_SECURITY = 'PHYSICAL_SECURITY',
    NEW_SHIPMENT = 'NEW_SHIPMENT',
    SHIFT_SUPERVISOR = 'SHIFT_SUPERVISOR',
    DEPUTY_HEAD_OF_WHEREHOUSE = 'DEPUTY_HEAD_OF_WHEREHOUSE',
    PLACEMENT_ADMIN = 'PLACEMENT_ADMIN',
    CHIEF_STOREKEEPER = 'CHIEF_STOREKEEPER',
}

export const RolesMapper = {
    [`${ROLE_PREFIX}Первичная приемка`]: Roles.INITIAL_RECEIVING,
    [`${ROLE_PREFIX}Приемка`]: Roles.RECEIVING,
    [`${ROLE_PREFIX}ЦТЭ`]: Roles.RETURNS,
    [`${ROLE_PREFIX}Автозапуск`]: Roles.AUTOSTART,
    [`${ROLE_PREFIX}Настройка СГ`]: Roles.SHELFLIFE,
    [`${ROLE_PREFIX}Упаковка`]: Roles.PACKING,
    [`${ROLE_PREFIX}Сортировка по СД`]: Roles.DROPPING,
    [`${ROLE_PREFIX}TESTER`]: Roles.TESTER,
    [`${ROLE_PREFIX}SCE-Administrator`]: Roles.SCE_ADMIN,
    [`${ROLE_PREFIX}SCE-Receiving Clerk`]: Roles.SCE_CLERK,
    [`${ROLE_PREFIX}Консолидация несоответствующих тар`]: Roles.ANOMALY_CONSOLIDATION,
    [`${ROLE_PREFIX}Отбор`]: Roles.PICKING,
    [`${ROLE_PREFIX}Мультиотбор`]: Roles.MULTI_PICKING,
    [`${ROLE_PREFIX}Отгрузка`]: Roles.SHIPMENT,
    [`${ROLE_PREFIX}Отгрузка ТС`]: Roles.NEW_SHIPMENT,
    [`${ROLE_PREFIX}Настройка УИТов`]: Roles.UIT_SETTINGS,
    [`${ROLE_PREFIX}Безуитная приемка`]: Roles.UIT_FREE,
    [`${ROLE_PREFIX}SCE-RF User`]: Roles.SCE_RF_USER,
    [`${ROLE_PREFIX}Редактирование несоответствующих тар`]: Roles.ANOMALY_ADMIN,
    [`${ROLE_PREFIX}Перепечать Этикеток УИТа`]: Roles.UIT_REPRINT,
    [`${ROLE_PREFIX}Отгрузка несоответствий`]: Roles.ANOMALY_RELOCATION,
    [`${ROLE_PREFIX}YM-Outbound Clerk`]: Roles.OUTBOUND_CLERK,
    [`${ROLE_PREFIX}Пересоздание TO и SO`]: Roles.CONVEYOR_TESTER,
    [`${ROLE_PREFIX}Администратор Сортировщика`]: Roles.SORTER_ADMIN,
    [`${ROLE_PREFIX}Инвентаризация`]: Roles.INVENTORIZATION,
    [`${ROLE_PREFIX}Администратор конвейера на приёмке`]: Roles.RECEIVING_TRANSPORT_ADMIN,
    [`${ROLE_PREFIX}Размещение`]: Roles.PLACEMENT,
    [`${ROLE_PREFIX}Оператор Ручных Волн`]: Roles.MANUAL_WAVES,
    [`${ROLE_PREFIX}Отмена приемки УИТа`]: Roles.DELETE_UIT,
    [`${ROLE_PREFIX}Оператор конвейерной приёмки`]: Roles.RECEIVING_CONVEYOR_OPERATOR,
    [`${ROLE_PREFIX}СБ`]: Roles.PHYSICAL_SECURITY,
    [`${ROLE_PREFIX}Старший смены`]: Roles.SHIFT_SUPERVISOR,
    [`${ROLE_PREFIX}Заместитель руководителя склада`]: Roles.DEPUTY_HEAD_OF_WHEREHOUSE,
    [`${ROLE_PREFIX}Администратор размещения и перемещений`]: Roles.PLACEMENT_ADMIN,
    [`${ROLE_PREFIX}Старший кладовщик`]: Roles.CHIEF_STOREKEEPER,
};
