import { FormDataResponse } from './types';

export const REPORT_FORM_DATA: FormDataResponse = {
    header: {
        code: 'test report',
        name: 'test report',
        group: 'Test',
        directPrint: true,
        offerGeneratedReportReuse: true,
    },
    parameters: [
        {
            caption: 'Курьерская служба',
            code: '1',
            required: true,
            stringValue: 'DPD',
            paramType: 'STRING',
        },
        {
            caption: 'Дата',
            code: '2',
            required: true,
            dateValue: '1970-01-01T00:00:01.000Z',
            paramType: 'DATE',
        },
        {
            caption: 'Целое',
            code: '4',
            required: true,
            numberValue: 5,
            paramType: 'INTEGER',
        },
        {
            caption: 'Дробное',
            code: '5',
            required: true,
            numberValue: 5.12,
            paramType: 'FLOAT',
        },
        {
            caption: 'Мульти список',
            code: '6',
            required: true,
            allowedValues: ['a', 'b', 'c', 'd', 'e'],
            dynamicList: true,
            paramType: 'MULTILIST',
            listValue: ['a', 'b'],
        },
        {
            caption: 'Список',
            code: '7',
            required: true,
            allowedValues: ['a', 'b', 'c', 'd', 'e'],
            dynamicList: true,
            paramType: 'LIST',
            listValue: ['a'],
        },

        {
            caption: 'Мульти список',
            code: '8',
            required: true,
            allowedValues: ['a', 'b', 'c', 'd', 'e'],
            dynamicList: false,
            paramType: 'MULTILIST',
        },
        {
            caption: 'Список',
            code: '9',
            required: true,
            allowedValues: ['a', 'b', 'c', 'd', 'e'],
            dynamicList: false,
            paramType: 'LIST',
        },
        {
            caption: 'Дата время',
            code: '10',
            required: true,
            dateValue: '1970-05-01T00:00:01.000Z',
            paramType: 'DATETIME',
        },
        {
            caption: 'Время',
            code: '11',
            required: true,
            timeValue: '14:15:00.000000000',
            paramType: 'TIME',
        },
        {
            caption: 'Местное дата время',
            code: '12',
            required: true,
            localDateTimeValue: '1970-05-01T00:00:01.000',
            paramType: 'LOCAL_DATETIME',
        },
        {
            caption: 'Местная дата',
            code: '13',
            required: true,
            localDateValue: '1970-05-01',
            paramType: 'LOCAL_DATE',
        },
        {
            caption: 'Местное время',
            code: '14',
            required: true,
            localTimeValue: '05:00:01.000',
            paramType: 'LOCAL_TIME',
        },
    ],
};
